apiVersion: v1
kind: Service
metadata:
  name: svc-java-demo
  namespace: ns-app
spec:
  selector:
    app: java-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
